<?php
$realm = 'Example';

//Check if we have entered authentication information, if we have not the user will be provided an authentication form.
if(empty($_SERVER['PHP_AUTH_DIGEST'])){
  login($realm);
}

$digest_parse = parse_http_digest($_SERVER['PHP_AUTH_DIGEST']);

$username_user = "test";
$password_user = "12345";

//When the client receives the response we need to compute a return hash. We need to compute it with the following steps:
//1. A1 = MD5(username:realm:password)
//2. A2 = MD5(method: digestURI)
//3. response = MD5(A1:nonce:A2)
//To validate if the credentials are corrent we will compare the $valid_response with the digest_parse['response'].

//Get the required parameters for the calculations.
$URI = $digest_parse['uri'];
$request_method = $_SERVER['REQUEST_METHOD'];
$nonce = $digest_parse['nonce'];
$nc = $digest_parse['nc'];
$cnonce = $digest_parse['cnonce'];
$qop = $digest_parse['qop'];
$response = $digest_parse['response'];

$A1 = md5($username_user . ':' . $realm . ':' . $password_user);
$A2 = md5($request_method . ':' . $URI);
$valid_response = md5($A1 . ':' . $nonce . ':' . $nc . ':' . $cnonce . ':' . $qop . ':' . $A2);

//Compare the response hash from the WWW-Authenticate form with the newly calculated hash using the username and password. If these matches we have the right credentials.
if ($response != $valid_response){
  die('Wrong credentials!');
}

//Valid username & password
echo 'You are logged in as: ' . $username_user;

//This function will generate a nonce, opaque value and present the authentication form to the user.
function login($realm){
  //Generate unique ID. Should be unique for every request. The nonce will be used by the client to generate a hash to send back to the server.
  $nonce =  md5(uniqid());
  //This is a unique string that should be generated by the server, we expect this value to be unaltered when the client sends it.
  $opaque = md5($realm);
  //Use all of these values and compose the WWW-Authenticate response to the client. This will be the popup form with username and password.
  header(sprintf('WWW-Authenticate: Digest realm="%s", qop="auth", nonce="%s", opaque="%s"', $realm, $nonce, $opaque));
  //If the user clicked cancel on the authentication form.
  die('User denied authentication form.');
}

//Decode the data the client sent us.
function parse_http_digest($PHP_AUTH_DIGEST)
{
    // protect against missing data
    $needed_parts = array('nonce'=>1, 'nc'=>1, 'cnonce'=>1, 'qop'=>1, 'username'=>1, 'uri'=>1, 'response'=>1);
    $digest_parse = array();
    $keys = implode('|', array_keys($needed_parts));

    preg_match_all('@(' . $keys . ')=(?:([\'"])([^\2]+?)\2|([^\s,]+))@', $PHP_AUTH_DIGEST, $matches, PREG_SET_ORDER);

    //Go through all needed parts and check if they exist.
    foreach ($matches as $m) {
        $digest_parse[$m[1]] = $m[3] ? $m[3] : $m[4];
        unset($needed_parts[$m[1]]);
    }

    //If we don't have all the parts return false, else return the digest data.
    if($needed_parts){
      return false;
    }else{
      return $digest_parse;
    }
}
?>
